version: 3.9

services:
  fail2web:
    image: monogramm/docker-fail2web
    container_name: fail2web
    restart: always
    ports:
      - "8018:8018"
    environment:
      - FAIL2REST_ADDR=http://191.101.2.248:5019/
      - FAIL2REST_USER=Admin
      - FAIL2REST_PASSWD=fXCwSoe$z8E2debr$PDAxJQ53fmNY!
    volumes:
      - /srv/fail2web/:/srv/fail2web/
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  fail2rest:
    image: monogramm/docker-fail2rest
    container_name: fail2rest
    restart: always
    ports:
      - "5019:5019"
    volumes:
      - /srv/fail2rest/:/srv/fail2rest/
      # Mount directory containing fail2ban.sock
      - /var/run/fail2ban/:/var/run/fail2ban/
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
